name: Build the documentation.

# build the documentation whenever there are new commits on main
# code from the mantra repository
on:
  push:
    # Alternative: only build for tags.
    tags:
      - '*'
  workflow_dispatch:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'
          #cache: 'poetry'
      - uses: abatilo/actions-poetry@v3.0.1

      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      
      - uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      
      - name: Install dependencies
        run: |
          poetry install

      # ADJUST THIS: install all dependencies (including pdoc)
      #- name: Install magnipy
      #  run: |
      #    pip install -e .

      - name: Install sphinx
        run: |
          poetry add sphinx sphinx_rtd_theme myst_parser

      - name: Sphinx build
        run: |
          poetry run sphinx-build docs/source docs/build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4